### ISSUE TITLE
libs/{libname} redirects are broken

### ISSUE THREAD

**Issue by sdarwin** [boostorg/website-v2#1007]
On the old website boost.org a URL with this format: 

https://www.boost.org/libs/unordered

redirects to

https://www.boost.org/doc/libs/1_84_0/libs/unordered/doc/html/unordered.html

It goes to the latest documentation of the library.  A boost developer has requested this functionality for the new website also.

**Comment by sdarwin** [comment]
On the new website this is a valid URL: https://www.boost.io/libraries/unordered/

Therefore perhaps the most straight-forward solution is to simply add routes like this.

https://www.boost.io/libs/unordered/ -> https://www.boost.io/libraries/unordered/

And that's it.  

 As long as the link isn't showing a 404, and it link to what we consider the main page for the library.

**Comment by vinniefalco** [comment]
I don't like having /libraries/ can we please change it to /libs/? Having /libs point to /libraries is an unnecessary extra complication. Just make it /libs/

**Comment by frankwiles** [comment]
@vinniefalco we can definitely do that, but if we make `/libraries/unordered/` be `/libs/unordered/` then we cannot do the original intent of this ticket.  It would have to be the library detail page and not the latest docs.  

It's not a big deal, but part of why we picked `/libraries/` originally was partly SEO (small improvement to have whole word in the URL) but also so we didn't get in the way of that redirect I believe.

**Comment by frankwiles** [comment]
heh yeah just let me know what you want to do here @vinniefalco

**Comment by 4down** [comment]
I'd say that making the old links continue to work, while maintaining the canonical URLs as still using /libraries (since the SEO part is important), would make the most sense.

So if we think it is of benefit that existing users who are accustomed to seeing /libs/ in the URL and have it either bookmarked or they're following a link from the docs that works on the existing site, would continue seeing /libs/ there in the address bar, that's fine, but the pages should then have a reference to the canonical URL as being /libraries and a user getting to the libraries section by first coming to boost.io would be seeing the URL as /libraries.

_The connection with the doc URL, would make more sense to me if the URL were /libs/docs/..  I'm not exactly even sure why the /libs/ is part of the doc URL except just that that's how it's always been.  It would make more sense to me if it were /doc/boost_1_84_0/libs/ from a hierarchical standpoint?  But I'm not wanting to really steer the conversation this way._

I think the front-facing website which has the purpose of introducing people to Boost, and so is in a way the "marketing" side of things, should have the best practices for SEO adhered to since that will only help bring new people to find the docs. 

But I'll defer to @vinniefalco on this too, just chiming in with my thoughts.

**Comment by vinniefalco** [comment]
The new website must strive to preserve identically, the functionality of the old site. Only when we have thoroughly ported everything that users of the old site expect should we then contemplate innovations. Applying this principle to this issue, we should:

1. make https://boost.io/libs/X redirects to the documentation page for X
2. make https://boost.io/libraries/X bring up the Library Detail page

Google doesn't seem to index simple redirects, and we want Google to not index libs/X so that's fine. Google will index libraries/, and that is an SEO-optional name so we are also good there.
