### ISSUE TITLE
[regression] list and category views not working on www.stage.boost.cppalliance.org

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1046]
On www.stage.boost.cppalliance.org/libraries, clicking on "List View" or "Category View" does nothing. These buttons work OK in boost.io. I suspect this may be related to the introduction of the "?version=boost-1-84-0" query parameter.

**Comment by sdarwin** [comment]
additional parameters were not added.  "?version=boost-1-81-0" works on boost.io.

Something else though.. the website "knows" what the latest version is.  After having been on "?version=boost-1-81-0", if someone actively selects "?version=boost-1-84-0"  it should probably clear the query parameter and cookie.   Now both of those are defaults which is "nothing".   Then in the future when 1-86-0 is released, that user will see 1-86-0 if they visit the website, because that is what "no query parameter" will mean at that time. The default being the latest version.

**Comment by kennethreitz** [comment]
This functionality should be restored now.
