### ISSUE TITLE
Version Dropdown Behavior

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#1096]
The version dropdown which appears on the Libraries, Library, and Releases page should work thusly:

1. All dropdowns show identical menu contents

2. All dropdowns include master and develop

3. When master or develop is chosen on the Releases page, instead of showing a release (which does not exist) we show an informational callout box explaining that there are no master or develop releases, along with a link to navigate them to the current release.

Consider moving master and develop to the bottom.

**Comment by kennethreitz** [comment]
We want master/develop at the bottom of the page too.

**Comment by kennethreitz** [comment]
The code is already written and merged to exclude master/develop in all three drop-downs (which all have separate code). This will get us to a good spot before launch.

Including custom ordering for the dropdrowns is extremely untriiial, unfortunately, due to the way Django is designed, so "simply including master/develop at the bottom of the list" is a surprisingly tall order. I tried about 45 different ways to do this, without any avail. 

We can likely do it, but it's going to have to wait until after launch. We're in a good spot at the moment! re: #1080.

**Comment by vinniefalco** [comment]
Excluding master and develop from all the drop-downs is the next best thing, yes.

Just an aside, not actionable, but what do you think of putting an ascii 127 character at the beginning of the words "master" and "develop" so they sort to the bottom? :)

**Comment by kennethreitz** [comment]
That's a good solution! We can do that through the admin.

**Comment by rbbeeston** [comment]
I'm not seeing Develop and Master in the dropdown, is this still an issue?
