### ISSUE TITLE
Make Libraries display mode persistent

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1106]
The libraries section can display the directory of libraries in three modes:

* Grid view (the default)
* List view
* Category view

These modes are not remembered and the page defaults to grid every time is revisited. Make this persistent via a user cookie.

**Comment by sdarwin** [comment]
From the recent discussions on reddit, users do care about web performance and load times. How could this feature be implemented without disrupting caching?  Consider, there is a difference between cookies and session variables.   What was done when remembering the boost version number was to assign the user a unique session id via a cookie, and store the version number as a session variable on the backend.   Since the browser cookie is unique for every user, it prevents caching.    
What could be done for library display mode, instead of session variables:  

Grid view (the default) - (no cookie)
List view - (cookie: library-mode: list)
Category view (cookie: library-mode: cat)

When a cookie exists, it varies between a limited set of distinct values. Two choices.  It should be possible the cache will serve  those versions of the page.

**Comment by kennethreitz** [comment]
These aren't just different button clicks, but separate, different URLs and views. We'd have to implement more redirection magic to make this work. 

Sam's suggestion of session store details is good, but I think overall this is a bad idea that just further complicates the codebase.

**Comment by kennethreitz** [comment]
@joaquintides feel free to test on staging, once this deploy goes up. It should work for unauthenticated users now too.

**Comment by vinniefalco** [comment]
Maybe the page has all three modes already rendered on it and the cookie just decides which one is visible using some kind of CSS hack. This way the cache holds the whole thing as one page.

**Comment by joaquintides** [comment]
@kennethreitz, works fine for me, both in unregistered and registered mode. 

* Redirection rules such as https://www.stage.boost.cppalliance.org/doc/ --> https://www.stage.boost.cppalliance.org/libraries continue to work, and the display mode is respected even in this case, so, perfect!
* I noticed that the cookie for this is not erased when an anonymous user goes logged in, but it is the other way around --this is perfectly ok, just wanted to mention.

@vinniefalco what would the advantage be of having all three display modes "hidden" in the same page? I don't think there's much difference between caching one or three pages from the point of view of CDN efficiency.

**Comment by sdarwin** [comment]
> the point of view of CDN efficiency

There are low variability cookies, as I mentioned in an earlier comment, and then there are high variability cookies `config-sessionid` which cause the page to become uncachable.  The latter seems to be used. So caching will not happen on these pages any more.  At least, the best case is that as long as an anonymous user doesn't click on any alternate views, such as category view, and stays with the default, it may still be ok.

**Comment by joaquintides** [comment]
Total noob here, but looks like this cookie can only take the values "libraries-mini" and "libraries-by-category"?

https://github.com/boostorg/website-v2/pull/1129/files

**Comment by sdarwin** [comment]
@joaquintides The way it is currently implemented, there is one cookie in the browser which is your sessionid.  On the backend in the database, a session has any number of session variables. One such variable SELECTED_LIBRARY_VIEW_SESSION_KEY might have the values "libraries-mini" or "libraries-by-category"...    "the session variable can only take the values ___"

**Comment by joaquintides** [comment]
Understood, thanks for the clarification.

**Comment by vinniefalco** [comment]
So, at the risk of exposing myself to be a noob at CSS, it may be possible to have the cookie as a client-side variable. And then the CSS can use a formula to determine which of the three panels to make visible. This would all happen in the client. The database would not be involved in this.
