### ISSUE TITLE
Style updates to website-V2

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1180]
1. Replace boost logo in nav bar with "B" icon.
2. change nav bar bottom border to give depth
3. in dark theme, change body text color to #e6e6e6

**Comment by mborland** [comment]
I am not sure if this is the correct place to comment, but code blocks under dark mode are unreadable. See below:

![Screenshot 2024-10-04 at 1 52 07 PM](https://github.com/user-attachments/assets/fa056095-21b2-4477-bea2-690ed7a917ba)

CC: @joaquintides since I see this is open but listed as Done in the project.

**Comment by rbbeeston** [comment]
Hi @mborland,

We are aware of this, but it's being handled in other tickets, mainly as part of the boostlook project to standardize the doc views.
