### ISSUE TITLE
Very old releases should be hosted

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#1230]
The oldest release versions are hosted on SourceForge. We should download them all into our archives so they are served from one place. And pages like this should have our download link:

https://www.stage.boost.cppalliance.org/releases/boost-1-21-1/

![image](https://github.com/user-attachments/assets/2fa64456-2baa-4ca0-b8f4-d60adb1f128b)

**Comment by sdarwin** [comment]
Sourceforge files are here: https://sourceforge.net/projects/boost/files/boost/
Current boost downloads are hosted at : https://archives.boost.io/
Notice that each archive is accompanied by a json file with this format:

```
{
"commit": "65c1319bb92fe7a9a4abd588eff5818d9c2bccf9",
"file": "boost_1_86_0.zip",
"created": "2024-08-07T22:03:02Z",
"sha256": "cd20a5694e753683e1dc2ee10e2d1bb11704e65893ebcc6ced234ba68e5d8646"
}
```

- git commit
- filename
- creation date
- The sha256 hash of the archive itself.

Action items:  write and test a python or bash script which does the following:
- downloads all sourceforge archives before version 1.63.0.
- generates a json file for each archive
- downloads all the archives a second time in order to re-check and re-verifying the sha hash. 
- arrange the downloads in the directory structure that archives.boost.io uses.  The destination will be an S3 bucket s3://boost-archives.   Directory format:

boost-archives/release/1.62.0/source/_filename_
boost-archives/release/1.61.0/source/_filename_
boost-archives/release/1.60.0/source/_filename_

-  Finally, an "aws s3 cp" command to upload the files to a bucket such as  s3://boost-archives/release/ .    

- Test the entire process with another test s3 bucket first.   If an S3 bucket is needed let me know.

- After the script is ready and tested, provide me a copy of the script.   I will run that "in production".

@rbbeeston  you could assign this to one of the developers.

**Comment by rbbeeston** [comment]
when this is complete, revisit https://github.com/boostorg/website-v2/issues/584

**Comment by gavinwahl** [comment]
@sdarwin do we have a way to get the commit (for the json file) for sourceforge releases?

**Comment by sdarwin** [comment]
@gavinwahl 

reference the git tags in https://github.com/boostorg/boost

From there,

commit 65c1319bb92fe7a9a4abd588eff5818d9c2bccf9 (HEAD, tag: boost-1.86.0)

matches the example in this issue above,

"commit": "65c1319bb92fe7a9a4abd588eff5818d9c2bccf9"

**Comment by GregKaleka** [comment]
@gavinwahl apologies - I missed that this was assigned to you. I've been working on this since yesterday per [this slack thread](https://cpplang.slack.com/archives/C0610TPQMAR/p1730919453857039). Let's connect tomorrow and compare notes. If you'd like to peek at what I have so far, you can look at [this very WIP commit](https://github.com/boostorg/website-v2/commit/c7e6416647740750c37e4c9447afe95205277c7b).

**Comment by GregKaleka** [comment]
Per your question above, note that we have commit SHAs stored in the db already via `Version.data["commit"]["sha"]`.

**Comment by gavinwahl** [comment]
Sourceforge has an rss feed for all downloads, might be easier than scraping their html: https://sourceforge.net/projects/boost/rss?limit=100000

It also includes md5sums, which would be more reliable to verify instead of downloading the file twice.

**Comment by sdarwin** [comment]
> md5 checksums

Yes, good idea

> stored in the db already via Version.data["commit"]["sha"].

I had envisioned this as a one-time cli-driven external script.  it wouldn't necessarily have access to the database, right?   The commit can be found in this way:  

git rev-list -n 1 $TAG

git rev-list -n 1 boost-1.86.0

**Comment by gavinwahl** [comment]
@rbbeeston both me and Greg started on this independently -- who do you want to finish it?

**Comment by rbbeeston** [comment]
@gavinwahl & @GregKaleka, can you compare notes on it and see who's further along?  @gavinwahl I see you don't have #1230 marked in progress yet, and have a couple other items still in progress. can you update your prioritizations so I can see what you currently have to work on?

Thanks!

**Comment by GregKaleka** [comment]
> md5 checksums
> Yes, good idea

That's fine with me - though boost.org and all the newer versions we host show SHA256 hashes.

**Comment by sdarwin** [comment]
The sha256 ought to be computed. The contents of the json would include the sha256.

The purpose of the md5 is limited - it is to double-check the download from sourceforge was correct.  Just for that step it can be used.

**Comment by GregKaleka** [comment]
OK, I've got a version of this working on the `sourceforge-import` branch. I ran the script, using a test bucket, and it appears to be working as expected. After running it, I verified the files seem to be stored correctly:

```python
In [1]: from storages.backends.s3boto3 import S3Boto3Storage
   ...: storage = S3Boto3Storage(bucket_name="stage-rob.boost.org.v2")
   ...: directory_path = "test/boost-archives/release/1.62.0/source/"
   ...: files = storage.listdir(directory_path)[1]
   ...:
   ...: for file in files:
   ...:     print(file)
   ...:
boost_1_62_0.7z
boost_1_62_0.7z.json
boost_1_62_0.tar.bz2
boost_1_62_0.tar.bz2.json
boost_1_62_0.tar.gz
boost_1_62_0.tar.gz.json
boost_1_62_0.zip
boost_1_62_0.zip.json

In [2]: with storage.open(file_name, mode='r') as json_file:
   ...:     content = json.load(json_file)
   ...:     print(json.dumps(content, indent=4))
   ...:
{
    "commit": "4f2bdeb93a4be13ba0dc5e9f44920a2bf67191fc",
    "file": "boost_1_62_0.tar.gz",
    "created": "2016-09-28T14:18:40Z",
    "sha256": "440a59f8bc4023dbe6285c9998b0f7fa288468b889746b1ef00e8b36c559dce1"
}
```

Right now my script is scraping the webpage. I'm going to modify it to use the RSS feed as Gavin suggested, so that I can access the MD5 checksum for verification (it's not readily available on webpage).

**Comment by GregKaleka** [comment]
OK, @sdarwin I've completed testing of this script. I don't have UI access to our S3 buckets, but if you'd like to do some checking, the tested files have been stored in the bucket `stage-rob.boost.org.v2` and are stored in the directory `test/boost-archives/release`.

Let me know if you need anything else from me to verify this worked.

If you're ready to run this "in production", you can check out the `sourceforge-import` branch, and change the constants `BUCKET_NAME` and `S3_KEY_PREFIX` at the top of the file `versions/management/commands/host_sourceforge_release_files.py`. You'll also need to ensure your AWS credentials are set correctly in your `.env` file. Specifically:

```
AWS_S3_ENDPOINT_URL="https://s3.us-east-2.amazonaws.com"
AWS_ACCESS_KEY_ID="foo"
AWS_SECRET_ACCESS_KEY="bar"
AWS_S3_REGION_NAME="us-east-2"

**Comment by sdarwin** [comment]
In a test environment, going file by file, the script is uploading to S3.  Great!!   Probably on Monday I will run it "live" then.

**Comment by sdarwin** [comment]
The main set of archives (zip, 7z, bz2, gz) advertised on boost.org and boost.io have been uploaded from sourceforge.  
https://archives.boost.io/release/1.62.0/source/
