### ISSUE TITLE
Implement django manifeststaticfilesstorage

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2#1321]
Suggested by @brianjp93 to add the following to possibly fix the css caching problems when moving to staging or prod
https://docs.djangoproject.com/en/5.1/ref/contrib/staticfiles/#manifeststaticfilesstorage

Setting as high priority as it could save more time in the long run

**Comment by sdarwin** [comment]
Submitted a PR to purge the cache, which should solve the problem in this issue.   
At the same time, there is an open issue with Fastly, manifeststaticfilesstorage could possibly still be interesting.  For now, wait and see.

**Comment by rbbeeston** [comment]
I assume the purge is a one time thing. it would be good to resolve this so it's not an issue every merge.  You'd like me to hold on this until we hear back from fastly? Any idea what the timeline is on that? Thanks!

**Comment by sdarwin** [comment]
I think we should go step-by-step and investigate the problem, while it's happening.

- On staging, static/css/styles.css is supposed to have a TTL of 5 minutes.  Has it ever exhibited the issue?  
- The new GHA purge will now run on each deploy.  That's "one time" per merge, per pull request.   What if this purge doesn't always solve it.   We should collect evidence.  Report the bug here, about which css file is out-of-date.

Fastly usually replies within 1-2 days.

In the meantime, if there is a deploy to production, you can log into Fastly and "Purge All" on boost.io.

**Comment by rbbeeston** [comment]
sounds good, as there are 3 possible css files that could be the issue, we should be able to tell which file is being missed.

**Comment by rbbeeston** [comment]
This no longer seems needed
