### ISSUE TITLE
Warn if library has no Readme

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#1339]
When a library does not have a README.md or README.adoc, the panel should still appear and there should be a message which urges the author or the visitor to contribute one:

"This library has no README.adoc, consider contributing one or send physical mail to the author at 1234 Lane Rd."

**Comment by GregKaleka** [comment]
I opened a small PR to handle this - open to feedback. I didn't include the physical address bit, since I'm not sure where that info would come from. I don't see any address fields on the library model, nor the User model (where we could grab it from the authors field).

Apologies if the "mail the README" bit is a joke and I'm taking it too seriously 😊.

**Comment by vinniefalco** [comment]
The problem can be seen here:

![image](https://github.com/user-attachments/assets/858eb7f7-298e-4fb5-97a3-ebb7b43eea29)

In between the "This Release" and "All Time" should be a README card, even if there is no README file. And in this case where there is no file we should put up a big sign in flashing lights that says "pretty please...with a cherry on top... add a f'king readme"
