### ISSUE TITLE
Search widget should use `latest` URLs

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2#1549]
Currently, the search widget, which indexes the latest Boost release (1.87 as of this writing), returns links containing that specific version. For instance, "concurrent_factory" returns

https://www.boost.io/doc/libs/1_87_0/libs/flyweight/doc/reference/factories.html#concurrent_factory_synopsis

etc. It'd be better if it returned

https://www.boost.io/doc/libs/latest/libs/flyweight/doc/reference/factories.html#concurrent_factory_synopsis

instead.

**Comment by GregKaleka** [comment]
I'm not very familiar with how search works, but it seems like the fix might need to be in `boost-gecko` rather than this repo. Am I wrong about that?

I did try changing the `data-current-boost-version` attribute to `latest`, but got this unsurprising error message.

![Image](https://github.com/user-attachments/assets/7d0713f7-cdf1-40a3-b64a-41ad3e6e79b4)

**Comment by GregKaleka** [comment]
Maybe @ashtum could provide thoughts on how to proceed?
