### ISSUE TITLE
Releases version drop-down style to match other drop-downs

### ISSUE THREAD

**Issue by d-spencer-strickland** [boostorg/website-v2#536]
Wait for approval on the new style of the drop-downs in Libraries first, but if that's approved, or if not, whatever the styling ends up being, needs to be brought over to the version drop-down also.

**Comment by 4down** [comment]
@gregnewman The reason they aren't the same width is due to #748 

On my local build, they are the same size and I was digging through the CSS trying to figure out why there was a difference between mine and staging/prod, until I realized it could have something to do with the content - and then checked. :see_no_evil:

**Comment by rbbeeston** [comment]
This has been made consistent. no longer an issue
