### ISSUE TITLE
Some old docs missing

### ISSUE THREAD

**Issue by frankwiles** [boostorg/website-v2#900]
There are definitely lots of docs missing before 1.35.0, but then seems to be some sporadic docs missing for certain libraries in certain versions. 

Let's do a couple of things: 

- [ ] Write some quick spidering code to check that the index page for every Library/Version combo exists (i.e. does not return 404) and report on all the Library/versions combos that do
- [ ] Attempt to figure out why the docs are missing.  Is missing from the S3 bucket? Does it exist in there but maybe in a different structure?
- [ ] Work up a plan/recommendations for dealing with the missing ones.

**Comment by sdarwin** [comment]
Example 1:
https://www.preview.boost.org/libraries/algorithm/boost-1-35-0/ doesn't point to algorithm docs.
The reason is that libs/algorithm is missing docs, but it has two sub-directories algorithm/string/ and algorithm/minmax/ .  Those contain html content, or redirects.

Example 2:
https://www.stage.boost.cppalliance.org/libraries/date-time/boost-1-35-0/ doesn't point to date-time docs. However a page does exist https://www.stage.boost.cppalliance.org/doc/libs/boost_1_35_0/doc/html/date_time.html 

Example 3:
https://www.preview.boost.org/libraries/call-traits/boost-1-35-0/ doesn't point to call-traits docs. Checking the general list, docs for call-traits are here instead https://www.preview.boost.org/doc/libs/boost_1_35_0/libs/utility/call_traits.htm

more...

There are clues in https://www.preview.boost.org/doc/libs/boost_1_35_0/libs/libraries.htm However Example 1 and Example 3 are unusual enough that a very basic algorithm won't be enough to import those docs. It would require manual intervention (at least once).   Perhaps a portion of these, although not all of them, could leverage a "translation table" that says "for call-traits, versions 1.31 through 1.60, the docs are in this unusual location ___"  and "for algorithm, versions 1.31 through 1.40, the docs are in this other unusual location ___"    Check-in the translation table to git.  During a scheduled doc ingestion, consult the table.      

Since these are out-of-date docs, it is lower priority. but still interesting.

**Comment by sdarwin** [comment]
I've updated the gist "Preliminary report from most recent versions back to 1.61.0."   In almost all cases, documentation does exist, so it's a matter of processing those few special cases, in addition to the typical ones when importing.

**Comment by williln** [comment]
See also this commit, accidentally made to `develop` directly: https://github.com/cppalliance/temp-site/commit/c9cc3c49b32cedabeaa54237b53674ab29bf1332

**Comment by williln** [comment]
@sdarwin @4down Can you remind me what the earliest release we should import is? The earliest in S3 is 1.31.0 (but 1.33.0 is missing), but the earliest on the old versions list is 1.10.3 https://www.boost.org/users/history/

**Comment by 4down** [comment]
I'd think we want to capture every version the old site has, but looking at what the oldest ones have for their documentation, it seems we would only be able to include them in the Releases section and not Libraries.  (the ones I quickly looked through only had about a sentence or two for release notes and nothing specific to any libraries)

I'm not sure if there had been any discussion before I came on that might have said we could just forget about the earliest versions though.  Worst case we could create a static content page that would go over the release notes on all of the old versions, probably have it all on a single page.

**Comment by williln** [comment]
@4down So for Libraries, how far back should we go? S3 has docs back to 1.31.0, but is missing 1.33.0 (but has 1.33.1).

**Comment by sdarwin** [comment]
>  S3 has docs back to 1.31.0

That matches https://www.boost.org/users/history/  which also doesn't have docs before 1.31.0.

Ideally we should import _everything_, but the question is, in what format? It could also be a static content page, in site-docs, if there is very little information to display on the most early versions.

**Comment by williln** [comment]
## Outstanding issues (staging) 

_Note: I would assume these issues are the same for Production but I haven't run any commands there._ 

### Feedback needed 

- **Version 1.33.0**: Missing from S3, so no doc links can load for that version at all. 
- **All versions older than 1.31.0**: S3 only goes back to 1.31.0
- **Algorithm**, 1.32.0-1.49.0: Missing from libraries list page, wasn't able to find it on my own https://www.stage.boost.cppalliance.org/doc/libs/boost_1_49_0/libs/libraries.htm 
- **Detail**, 1.60.0 and older: Not in the list of libraries, and I wasn't able to find it on my own: https://www.stage.boost.cppalliance.org/doc/libs/boost_1_49_0/libs/libraries.htm 
- **Exception**, 1.35.0 and older: Not in the list of libraries: https://www.stage.boost.cppalliance.org/doc/libs/boost_1_35_0/libs/libraries.htm
- **GraphParallel**, 1.34.0-1.39.0: missing from list of libraries, but not located at the same location so still unknown
- **Identity Type**, 1.49.0 and older: Not in library list. 
- **IO**: 1.63.0 and older: Not in library list but is in gitmodules: https://github.com/boostorg/boost/blob/boost-1.60.0/.gitmodules#L69 
- *Log** 1.53.0 and older: Not on libraries list page https://www.stage.boost.cppalliance.org/doc/libs/boost_1_53_0/libs/libraries.htm but is in gitmodules https://github.com/boostorg/boost/blob/boost-1.53.0/.gitmodules#L165
- **WinAPI** 1.56.0-1.60.0: Not in library list but is in gitmodules 


### Still working, no feedback needed 

- **Container Hash**, 1.67.0-1.77.0: The fix for these versions is working locally, but not in staging. Still debugging. 
- **GraphParallel**, 1.62.0: Located at https://www.stage.boost.cppalliance.org/doc/libs/boost_1_62_0/libs/graph_parallel/doc/html/index.html, but missing from library list, so I'll add exception logic
- **Iterator**, 1.51.0 and older: Located https://www.stage.boost.cppalliance.org/doc/libs/boost_1_51_0/libs/iterator/doc/index.html, so I will add exception logic
- **Lexical Cast**, 1.58.0 and 1.56.0: not sure why these are not importing. Will investigate. 
- **Local Function**, 1.58.0, 1.56.0, 1.53.0, and 1.51.0: not sure why these are not importing. Will investigate 
- **Math Quaternion**: 1.58.0: exception logic not working. will investigate. 
- **Min-Max**, 1.58.0, 1.56.0, 1.53.0, 1.51.0, 1.48.0, etc.: exception logic not working.
- **Numeric Conversion**,  1.58.0, 1.56.0, 1.53.0, 1.51.0, 1.48.0, etc.: exception logic not working.
- **Result Of**,  1.58.0, 1.56.0, 1.53.0, 1.51.0, 1.48.0, etc.: exception logic not working.
- **Scope Exit**,  1.58.0, 1.56.0, 1.53.0, 1.51.0, 1.48.0, etc.: exception logic not working.
- **String Ref**: exception logic needs tweaking
- **ThrowException**, 1.58.0 and 1.56.0
- **TypeErasure**, 1.58.0 and 1.56.0
- **Type Index**, 1.58.0 and 1.56.0
- **Value Initialized*,  1.58.0, 1.56.0, 1.53.0, 1.51.0, 1.48.0, etc.: exception logic not working.

**Comment by williln** [comment]
@sdarwin This is the final set of exceptions: 

- Date Time, 1.31.0 only ([gitmodules](https://github.com/boostorg/boost/blob/boost-1.31.0/.gitmodules#L117))
- In Place, Typed In Place Factory: 1.31.0 
- Member Function: 1.58.0 (sublibrary of Bind, and exists in both older and newer versions -- only this one is missing)
- Numeric Conversion: 1.32.0-1.34.1 ([gitmodules 1.32.0](https://github.com/boostorg/boost/blob/boost-1.32.0/.gitmodules#L137))
- Type Traits: 1.31.0-1.34.1 ([gitmodules 1.31.0](https://github.com/boostorg/boost/blob/boost-1.31.0/.gitmodules#L41))

**Comment by sdarwin** [comment]
Hi @williln 

I have quickly checked two of those five, and the documentation is present.    Is there a question about these libraries?

- Date Time, 1.31.0 only (gitmodules)

https://www.boost.org/doc/libs/1_31_0/libs/date_time/doc/index.html
https://www.boost.io/doc/libs/1_31_0/libs/date_time/doc/index.html

- Numeric Conversion: 1.32.0-1.34.1 (gitmodules 1.32.0)

https://www.boost.org/doc/libs/1_32_0/libs/numeric/conversion/doc/index.html
https://www.boost.io/doc/libs/1_32_0/libs/numeric/conversion/doc/index.html

**Comment by rbbeeston** [comment]
It appears that everything here has been completed. If any items pop up, they will be dealt with on seperate tickets
