### ISSUE TITLE
Option to delete user data

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2#965]
Users need the option to delete their account, and we should ensure that all the information associated with that user is deleted. However, public information such as what is still on GitHub, may need to be preserved. If the user also deletes their public GitHub information (or makes it private) then we should strive to remove the information on our side as well.

**Comment by Lastique** [comment]
I think, besides the account deletion, there should be a way to delete particular pieces of content posted on the website. Such as forum posts, comments, etc.

**Comment by vinniefalco** [comment]
> Such as forum posts, comments, etc.

Well that's easy, as there is no forum and no way to leave comments :) Nor do we plan such a feature.

**Comment by joaquintides** [comment]
Let me propose a tentative spec for the user deletion feature for everyone to discuss:

* It's self-service (as opposed to having to request deletion to some website admin).
* What's deleted: all the info under "Profile"
* Contributions from the user (a this point, entries in News) are not deleted, the rationale being that those contributions have entered the public domain. **Currently this is not covered by the terms of use.**
  * We need to decide what to do with the icon shown alongside news posted by the (now deleted) user.
* There's an additional section in "Profile" named "Danger". Inside it, there's a differently colored button in the profile section with the tile "Delete my account".
* Pressing a button shows a windows similar to the one used at Github. The texts will be different but you get the idea.
![delete-github-2](https://github.com/boostorg/website-v2/assets/3283164/36e26c2f-875e-4100-abbb-839839aebd90)
* We request the user's email address and that s/he retype a message such as "delete my account".
* Pressing the button does the deletion and shows a popup with the message "_<email_address>_. Your account has been deleted", plus one button "Return to homepage". Pressing the button will bring the user to well, the homepage, in anonymous mode.

**Comment by joaquintides** [comment]
I'm not so sure this 10-day grace period is so necessary, given that, if we're not deleting the user's contributions, the only information deleted is that which appears on the profile section: name, picture, update preferences; nothing terribly valuable anyway.

**Comment by vinniefalco** [comment]
Sometimes people delete their account for emotional reasons which they soon regret.

**Comment by joaquintides** [comment]
As per the 06/28 meeting, let's implement immediate deletion and then we can continue with #1121

**Comment by joaquintides** [comment]
**GDPR compliance**

I've talked to an expert on GDPR here in Spain and the recommendations for us regarding GDPR compliance are:

**Physical vs. logical deletion**

It is recommended that we don't physically delete the user's data (email address, name, etc.) for a safeguard period of at least 6 months (some companies go beyond that limit and wait for a number of years), in case an authority requests this info (for a criminal investigation, for instance). After this safeguard period it is OK to physically remove the information (by purging the DB for instance).

While the user is logically deleted, it is required that the service does not use the affected information in any way --it's simply sitting there, but otherwise opaque to the entire service.

**Contributions from deleted users**

According to the TOU, contributions are licensed to us and we can keep news, articles, etc. uploaded by the deleted user. It is recommended that we remove personal information, like the name "Louis Tatta" and the avatar, as shown here:

![imagen](https://github.com/user-attachments/assets/1fc3e2b8-4278-4b26-a67f-1a0585909e3e)

**Hosting country for the user DB**

This is a very critical point. According to GDPR, storing personal information from EU citizens outside the EU is subjected to serious scrutiny. This has nothing to do with the company's registration country, we're talking about the physical location of the DB. In our case (assuming the current DB is located in the US), we have these options:

1. We move the user DB to the EU (for instance, to the Ireland region of AWS).
2. We enter the [EU-U.S. Data Privacy Framework](https://ec.europa.eu/commission/presscorner/detail/en/ip_23_3721), which basically requires that the C++ Alliance registers with the US branch of this framework.
3. We justify that the service needs be hosted in the US, inform the users about this and contact each and every national data security agency in EU to let them know.

3 is basically unfeasible, and 1 is by far the simplest solution, and this the recommended option.

**Comment by vinniefalco** [comment]
website avatars should have "Display Name" just like Slack

**Comment by vinniefalco** [comment]
I wouldn't mind doing 1 right away and also pursuing number 2 in parallel just in case

**Comment by gavinwahl** [comment]
@rbbeeston 
Merged, but will need some testing by someone more familiar with the application. The test case I did was to delete the user and then confirm that they could not log in again.
